#include <ExcelXlsxHelpers.hxx>

#include <BitVar.hxx>
#include <AnyTypeVar.hxx>
#include <DynVar.hxx>
#include <FloatVar.hxx>
#include <IntegerVar.hxx>
#include <LongVar.hxx>
#include <MappingVar.hxx>
#include <MixedVar.hxx>
#include <TextVar.hxx>
#include <TimeVar.hxx>
#include <UTF8Converter.hxx>

#include <algorithm>
#include <climits>
#include <unordered_map>
#include <unordered_set>
#include <cmath>
#include <ctime>
#include <memory>
#include <string>
#include <vector>

using namespace OpenXLSX;
using namespace ExcelXlsxCore;

namespace ExcelXlsxHelpers
{
  const Variable *unwrapAnyOrMixed(const Variable *val)
  {
    const Variable *current = val;

    while (current
        && (current->isA() == ANYTYPE_VAR || current->isA() == MIXED_VAR))
    {
      const AnyTypeVar *wrapped = static_cast<const AnyTypeVar *>(current);
      current = wrapped->getVar();
    }

    return current;
  }

  std::string toUtf8(const char *projectText)
  {
    if (Resources::isUtf8Encoding())
      return std::string(projectText);
    return std::string(UTF8Converter::toUTF8(CharString(projectText)).c_str());
  }

  CharString fromUtf8(const std::string &utf8)
  {
    if (Resources::isUtf8Encoding())
      return CharString(utf8.c_str());
    return UTF8Converter::fromUTF8(CharString(utf8.c_str()));
  }

  bool isRepresentable(const std::string &utf8)
  {
    return Resources::isUtf8Encoding() || toUtf8(fromUtf8(utf8).c_str()) == utf8;
  }
}

namespace
{
  constexpr size_t EXCEL_MAX_ROWS = 1048576;
  constexpr size_t EXCEL_MAX_COLUMNS = 16384;
  constexpr float EXCEL_MAX_COLUMN_WIDTH = 255.0f;

  // Cell text read from the file, escapes decoded. Stays UTF-8: reads may run
  // on worker threads, and WinCC OA's encoding converter is only used on the
  // CTRL thread (convertRowsToProjectEncoding).
  TextVar cellTextVar(const std::string &utf8)
  {
    return TextVar(decodeExcelEscapes(utf8).c_str());
  }

  // Cell text from project-encoded text via toXmlUtf8; width receives the
  // length in characters. False if the text exceeds Excel's per-cell limit.
  bool toCellText(const char *projectText, std::string &out, size_t &width)
  {
    std::string utf8 = ExcelXlsxHelpers::toUtf8(projectText);
    width = utf16Length(utf8);
    out = toXmlUtf8(utf8.c_str());
    return width <= EXCEL_MAX_CELL_CHARS;
  }

  // Set a mapping value using the cell type reported by OpenXLSX. Returns
  // false for an empty cell. A formula without a cached result (files
  // generated by tools and never recalculated by Excel) reads as "" but
  // counts as content. A date CTRL cannot hold reads as its Excel serial.
  bool setTypedCellCached(MappingVar &row, const Variable &key,
                          XLCell &cell,
                          const XLStyles &styles,
                          std::unordered_map<XLStyleIndex, bool> &dateCache,
                          ReadState &state)
  {
    XLCellValue val = cell.value();

    if (isUncachedFormula(cell, val))
    {
      row.setAt(key, TextVar(""));
      ++state.uncachedFormulas;
      return true;
    }

    CellNumber num;
    if (cellNumber(cell, val, num))
    {
      if (isDateNumber(num, cell, styles, dateCache))
      {
        std::tm tm{};
        PVSSshort milli = 0;
        time_t sec = 0;
        LocalTime converted = serialToLocalTime(num.value, tm, milli, sec, TimeVar::MaxTimeVarSec, state);
        if (converted == LocalTime::OutOfRange)
        {
          row.setAt(key, FloatVar(num.value));
          ++state.unrepresentableDates;
        }
        else
        {
          row.setAt(key, TimeVar(sec, milli));
          if (converted == LocalTime::Shifted)
            ++state.shiftedTimes;
        }
      }
      else if (num.isInteger)
      {
        if (num.integer >= INT_MIN && num.integer <= INT_MAX)
          row.setAt(key, IntegerVar(static_cast<int>(num.integer)));
        else
          row.setAt(key, LongVar(num.integer));
      }
      else
      {
        double intpart;
        if (modf(num.value, &intpart) == 0.0
         && intpart >= INT_MIN && intpart <= INT_MAX)
          row.setAt(key, IntegerVar(static_cast<int>(intpart)));
        else
          row.setAt(key, FloatVar(num.value));
      }
      return true;
    }

    switch (val.type())
    {
      case XLValueType::Boolean:
        row.setAt(key, BitVar(val.get<bool>()));
        return true;

      case XLValueType::String:
        row.setAt(key, cellTextVar(val.get<std::string>()));
        return true;

      case XLValueType::Error:
      {
        // Keep Excel's error code (#DIV/0!, #N/A, ...) so a failed formula is
        // distinguishable from an empty cell.
        std::string code = rawNumberText(cell);
        row.setAt(key, TextVar(code.empty() ? "#ERROR" : code.c_str()));
        return true;
      }

      default: // Empty
        row.setAt(key, TextVar(""));
        return false;
    }
  }

  //----------------------------------------------------------------------------
  // Write helpers
  //----------------------------------------------------------------------------

  // The row as a mapping (unwrapping anytype/mixed), or nullptr if it is not one.
  const MappingVar *asMapping(const Variable *rowVar)
  {
    const Variable *inner = ExcelXlsxHelpers::unwrapAnyOrMixed(rowVar);
    return (inner && inner->isA() == MAPPING_VAR)
      ? static_cast<const MappingVar *>(inner)
      : nullptr;
  }

  // Write a single WinCC OA Variable to an OpenXLSX cell. width receives the
  // displayed length for column sizing. False with a reason in problem if the
  // value cannot be stored in Excel.
  bool writeTypedCell(XLCell &cell, const Variable *val,
                      XLStyleIndex dateTimeFmtIdx, size_t &width,
                      std::string &problem)
  {
    width = 0;
    if (!val)
    {
      cell.value() = std::string();
      return true;
    }

    switch (val->isA())
    {
      case INTEGER_VAR:
      case LONG_VAR:
      {
        int64_t v = (val->isA() == INTEGER_VAR)
          ? static_cast<int64_t>(static_cast<const IntegerVar *>(val)->getValue())
          : static_cast<int64_t>(static_cast<const LongVar *>(val)->getValue());
        cell.value() = v;
        width = numberWidth(static_cast<double>(v));
        return true;
      }
      case FLOAT_VAR:
      {
        double v = static_cast<const FloatVar *>(val)->getValue();
        cell.value() = v;
        width = numberWidth(v);
        return true;
      }
      case BIT_VAR:
        cell.value() = static_cast<const BitVar *>(val)->isTrue();
        width = 5; // "FALSE"
        return true;
      case TIME_VAR:
      {
        const TimeVar *timeVal = static_cast<const TimeVar *>(val);
        double serial = 0.0;
        if (!localTimeToSerial(static_cast<time_t>(timeVal->getSeconds()),
                               timeVal->getMilli(), serial))
        {
          problem = "time cannot be converted to local time";
          return false;
        }
        cell.value() = XLDateTime(serial);
        cell.setCellFormat(dateTimeFmtIdx);
        width = 19; // "YYYY-MM-DD hh:mm:ss"
        return true;
      }
      case TEXT_VAR:
      {
        std::string text;
        if (!toCellText(static_cast<const TextVar *>(val)->getValue(), text, width))
        {
          problem = "text exceeds " + std::to_string(EXCEL_MAX_CELL_CHARS) + " characters";
          return false;
        }
        cell.value() = text;
        return true;
      }
      case ANYTYPE_VAR:
      case MIXED_VAR:
      {
        const Variable *inner = ExcelXlsxHelpers::unwrapAnyOrMixed(val);
        if (!inner)
        {
          cell.value() = std::string();
          return true;
        }

        return writeTypedCell(cell, inner, dateTimeFmtIdx, width, problem);
      }
      default:
      {
        CharString str = val->formatValue(CharString());
        std::string text;
        if (!toCellText(str.c_str(), text, width))
        {
          problem = "text exceeds " + std::to_string(EXCEL_MAX_CELL_CHARS) + " characters";
          return false;
        }
        cell.value() = text;
        return true;
      }
    }
  }
} // namespace

namespace ExcelXlsxHelpers
{
  // Read an open worksheet into a DynVar of MappingVar rows.
  void readSheetRows(XLWorksheet &wks, XLDocument &doc, DynVar &result,
                     bool useHeaders, bool skipHidden, bool skipEmpty,
                     std::vector<std::string> &warnings)
  {
    uint32_t rowCount = wks.rowCount();
    uint16_t colCount = wks.columnCount();

    if (rowCount == 0 || colCount == 0)
      return;

    // Pre-fetch styles once and cache format-index → is_date results so each
    // unique cell format is inspected only once across the entire sheet.
    XLStyles styles = doc.styles();
    std::unordered_map<XLStyleIndex, bool> dateCache;

    // One mapping key per column: the header text, or the 1-based column
    // number when headers are off or a header cell is empty. Repeated
    // headers get a numeric suffix ("Value", "Value_2") so no two columns
    // share a key and overwrite each other.
    std::vector<std::unique_ptr<Variable>> keys;
    keys.reserve(colCount);
    uint32_t dataStartRow = 1;

    ReadState state;

    if (useHeaders)
    {
      std::unordered_set<std::string> seen;
      forEachCell(wks, 1, colCount, [&](uint16_t index, XLCell *cell)
      {
        const uint16_t c = static_cast<uint16_t>(index + 1);
        std::string name = cell ? headerText(*cell, styles, dateCache, state) : std::string();
        if (name.empty())
        {
          keys.emplace_back(new IntegerVar(c));
          return;
        }

        // UTF-8 key; convertRowsToProjectEncoding converts it (and resolves
        // names that collide only after conversion) on the CTRL thread.
        std::string unique = name;
        for (int n = 2; !seen.insert(unique).second; ++n)
          unique = name + "_" + std::to_string(n);
        keys.emplace_back(new TextVar(unique.c_str()));
      });
      dataStartRow = 2;
    }

    for (uint16_t c = static_cast<uint16_t>(keys.size()) + 1; c <= colCount; ++c)
      keys.emplace_back(new IntegerVar(c));

    // Header-only sheet: rows(2, 1) would still yield one bogus row.
    if (dataStartRow > rowCount)
      return;

    // A row without any cells, appended for rows that do not exist when
    // empty rows are kept (so result index still maps to the Excel row).
    MappingVar emptyRow;
    if (!skipEmpty)
      for (const auto &key : keys)
        emptyRow.setAt(*key, TextVar(""));

    // Only rows that exist in the XML are visited cell by cell (see
    // forEachCell); rowExists() does not create missing rows.
    XLRowRange rows = wks.rows(dataStartRow, rowCount);
    for (auto it = rows.begin(); it != rows.end(); ++it)
    {
      if (!it.rowExists())
      {
        if (!skipEmpty)
          result.append(emptyRow);
        continue;
      }

      if (skipHidden && it->isHidden())
        continue;

      MappingVar rowMap;
      bool hasValue = false;
      forEachCell(wks, it.rowNumber(), colCount, [&](uint16_t c, XLCell *cell)
      {
        if (cell)
          hasValue = setTypedCellCached(rowMap, *keys[c], *cell, styles, dateCache, state) || hasValue;
        else
          rowMap.setAt(*keys[c], TextVar(""));
      });

      // rowCount() includes rows that only carry formatting (fill, height);
      // by default rows without any value are not records.
      if (hasValue || !skipEmpty)
        result.append(rowMap);
    }

    if (state.unrepresentableDates > 0)
      warnings.push_back(std::to_string(state.unrepresentableDates)
                         + " date cell(s) lie outside the range of CTRL time (1970 to 2262) and "
                           "read as their Excel serial number (float)");
    if (state.shiftedTimes > 0)
      warnings.push_back(std::to_string(state.shiftedTimes)
                         + " time(s) fall into the hour skipped when daylight saving time starts "
                           "and were moved to the next valid time");
    if (state.uncachedFormulas > 0)
      warnings.push_back(std::to_string(state.uncachedFormulas)
                         + " formula cell(s) have no calculated value and read as \"\"; "
                           "open and save the file in Excel to calculate them");
  }

  // Write a DynVar of MappingVars to an OpenXLSX worksheet. Columns are the
  // keys of all rows in order of first appearance; row 1 holds them as bold
  // headers.
  bool writeSheetData(XLWorksheet &wks, const DynVar &data, XLDocument &doc,
                      std::string &error)
  {
    unsigned int numRows = data.getNumberOfItems();
    if (numRows == 0)
      return true;

    // Validate every row before touching the sheet.
    std::vector<const MappingVar *> rows;
    rows.reserve(numRows);
    for (unsigned int r = 0; r < numRows; r++)
    {
      const MappingVar *row = asMapping(data.getAt(r));
      if (!row)
      {
        error = "row " + std::to_string(r + 1) + " is not a mapping";
        return false;
      }
      rows.push_back(row);
    }

    // Union of all keys, so keys missing from the first row are not dropped.
    // Lookups use the original key Variables: stringified TextVar keys would
    // miss non-text keys such as the int column keys readSheetRows produces.
    MappingVar seenKeys;
    std::vector<const Variable *> keys;
    for (const MappingVar *row : rows)
    {
      for (unsigned int k = 0; k < row->getNumberOfItems(); k++)
      {
        const Variable *key = row->getKey(k);
        if (!seenKeys.getAt(*key))
        {
          seenKeys.setAt(*key, BitVar(true));
          keys.push_back(key);
        }
      }
    }

    size_t numCols = keys.size();
    if (numCols == 0)
      return true;

    // Excel's sheet size; checked up front so nothing is half-written.
    if (numRows + 1 > EXCEL_MAX_ROWS)
    {
      error = std::to_string(numRows) + " rows exceed Excel's limit of "
            + std::to_string(EXCEL_MAX_ROWS - 1) + " data rows";
      return false;
    }
    if (numCols > EXCEL_MAX_COLUMNS)
    {
      error = std::to_string(numCols) + " columns exceed Excel's limit of "
            + std::to_string(EXCEL_MAX_COLUMNS);
      return false;
    }

    // Create bold cell format for the header row.
    // XLFont/XLCellFormat are XML-node proxies: call create() first to duplicate
    // the default entry, then modify the new entry so the default is not mutated.
    XLStyleIndex boldFmtIdx = createBoldHeaderFormat(doc);

    // Built-in format 22: date + time display. Without a date format, Excel
    // shows the serial value (e.g. 46105.837...).
    XLStyleIndex dateTimeFmtIdx = createDateTimeFormat(doc);

    // Max displayed width per column, starting with the header.
    std::vector<size_t> maxWidths(numCols);
    std::vector<std::string> headerNames(numCols);

    // Write column headers in row 1 (bold)
    for (size_t c = 0; c < numCols; c++)
    {
      CharString name = keys[c]->formatValue(CharString());
      headerNames[c] = toUtf8(name.c_str()); // for error messages (UTF-8)
      std::string text;
      if (!toCellText(name.c_str(), text, maxWidths[c]))
      {
        error = "column header exceeds " + std::to_string(EXCEL_MAX_CELL_CHARS) + " characters";
        return false;
      }

      auto cell = wks.cell(1, static_cast<uint16_t>(c + 1));
      cell.value() = text;
      cell.setCellFormat(boldFmtIdx);
    }

    // Write data rows starting from row 2
    for (unsigned int r = 0; r < numRows; r++)
    {
      for (size_t c = 0; c < numCols; c++)
      {
        const Variable *cellVal = rows[r]->getAt(*keys[c]);
        auto cell = wks.cell(
          static_cast<uint32_t>(r + 2),
          static_cast<uint16_t>(c + 1)
        );

        size_t width = 0;
        std::string problem;
        if (!writeTypedCell(cell, cellVal, dateTimeFmtIdx, width, problem))
        {
          error = "row " + std::to_string(r + 1) + ", column '"
                + headerNames[c] + "': " + problem;
          return false;
        }
        if (width > maxWidths[c])
          maxWidths[c] = width;
      }
    }

    // Set column widths (character width + padding, capped at Excel's maximum)
    for (size_t c = 0; c < numCols; c++)
      wks.column(static_cast<uint16_t>(c + 1))
          .setWidth(std::min(static_cast<float>(maxWidths[c]) + 2.0f, EXCEL_MAX_COLUMN_WIDTH));

    return true;
  }

  void convertRowsToProjectEncoding(DynVar &rows, std::vector<std::string> &warnings)
  {
    if (Resources::isUtf8Encoding())
      return;

    // Text keys converted once each and de-duplicated after conversion:
    // characters the codepage lacks can merge distinct UTF-8 names.
    std::unordered_map<std::string, std::string> keyMap; // UTF-8 -> project
    std::unordered_set<std::string> usedKeys;
    auto convertKey = [&](const std::string &utf8) -> const std::string &
    {
      auto known = keyMap.find(utf8);
      if (known != keyMap.end())
        return known->second;

      if (!isRepresentable(utf8))
        warnings.push_back("header '" + utf8 + "' cannot be represented in the project encoding");

      std::string base = fromUtf8(utf8).c_str();
      std::string unique = base;
      for (int n = 2; !usedKeys.insert(unique).second; ++n)
        unique = base + "_" + std::to_string(n);
      return keyMap.emplace(utf8, unique).first->second;
    };

    for (unsigned int r = 0; r < rows.getNumberOfItems(); r++)
    {
      const Variable *rowVar = rows.getAt(r);
      if (!rowVar || rowVar->isA() != MAPPING_VAR)
        continue;

      const MappingVar &row = *static_cast<const MappingVar *>(rowVar);
      MappingVar *converted = new MappingVar;
      for (unsigned int k = 0; k < row.getNumberOfItems(); k++)
      {
        const Variable *key = row.getKey(k);
        const Variable *value = row.getValue(k);

        Variable *newKey = (key->isA() == TEXT_VAR)
          ? new TextVar(convertKey(static_cast<const TextVar *>(key)->getValue()).c_str())
          : key->clone();
        Variable *newValue = (value->isA() == TEXT_VAR)
          ? new TextVar(fromUtf8(static_cast<const TextVar *>(value)->getValue()).c_str())
          : value->clone();
        converted->setAt(newKey, newValue); // takes ownership
      }
      delete rows.replaceAt(r, converted);
    }
  }
}
